import 'package:get/get.dart';

class Internationalization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_UK': {
      'sign_in': 'Sign In',
      'email_address': 'Email Address',
      'password': 'Password',
      'swipe_left': 'Don\'t have an account? Swipe left',
      'sign_up': 'Sign Up',
      'username': 'Username',
      'verify_password': 'Verify Password',
      'swipe_right': 'Already have an account? Swipe right',
      'good_afternoon': 'Good afternoon,',
      'expense_history': 'Expense History',
      'today': 'Today',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'appearance': 'Appearance',
      'light': 'Light',
      'dark': 'Dark',
      'language': 'Language',
      'english': 'English',
      'kazakh': 'Kazakh',
      'russian': 'Russian',
      'account_info': 'Account Info',
      'log_out': 'Log Out',
      'profile': 'Profile',
      'uncategorized': 'Uncategorized',
      'housing': 'Housing',
      'transportation': 'Transportation',
      'food': 'Food',
      'health_and_medical': 'Health and Medical',
      'personal_care': 'Personal Care',
      'entertainment': 'Entertainment',
      'debt_payments': 'Debt Payments',
      'education': 'Education',
      'clothing_and_accessories': 'Clothing and Accessories',
      'savings_and_investments': 'Savings and Investments',
      'top_spending_categories': 'Top Spending Categories',
      'statistics': 'Statistics',
      'week': 'Week',
      'month': 'Month',
      'year': 'Year',
      'monday': 'Mon',
      'tuesday': 'Tue',
      'wednesday': 'Wed',
      'thursday': 'Thu',
      'friday': 'Fri',
      'saturday': 'Sat',
      'sunday': 'Sun',
      'add_expense': 'Add Expense',
      'category': 'CATEGORY',
      'name': 'NAME',
      'amount': 'AMOUNT',
      'date': 'DATE',
      'add': 'Add',
      'home': 'Home',
      'wallet': 'Wallet',
    },
    'ru_RU': {
      'sign_in': 'Войти',
      'email_address': 'Электронная почта',
      'password': 'Пароль',
      'swipe_left': 'Нет аккаунта? Свайпай влево',
      'sign_up': 'Регистрация',
      'username': 'Имя пользователя',
      'verify_password': 'Подтвердите пароль',
      'swipe_right': 'Уже есть аккаунт? Свайпай вправо',
      'good_afternoon': 'Добрый вечер,',
      'expense_history': 'История расходов',
      'today': 'Сегодня',
      'this_week': 'Эта неделя',
      'this_month': 'Этот месяц',
      'appearance': 'Внешний вид',
      'light': 'Светлый',
      'dark': 'Темный',
      'language': 'Язык',
      'english': 'Английский',
      'kazakh': 'Казахский',
      'russian': 'Русский',
      'account_info': 'Информация об аккаунте',
      'log_out': 'Выход',
      'profile': 'Профиль',
      'uncategorized': 'Без категории',
      'housing': 'Жилье',
      'transportation': 'Транспорт',
      'food': 'Питание',
      'health_and_medical': 'Здоровье и медицина',
      'personal_care': 'Личный уход',
      'entertainment': 'Развлечения',
      'debt_payments': 'Оплаты по долгам',
      'education': 'Образование',
      'clothing_and_accessories': 'Одежда и аксессуары',
      'savings_and_investments': 'Сбережения и инвестиции',
      'top_spending_categories': 'Самые большие категории расходов',
      'statistics': 'Статистика',
      'week': 'Неделя',
      'month': 'Месяц',
      'year': 'Год',
      'monday': 'Пн',
      'tuesday': 'Вт',
      'wednesday': 'Ср',
      'thursday': 'Чт',
      'friday': 'Пт',
      'saturday': 'Сб',
      'sunday': 'Вс',
      'add_expense': 'Добавить расход',
      'category': 'КАТЕГОРИЯ',
      'name': 'ИМЯ',
      'amount': 'КОЛИЧЕСТВО',
      'date': 'ДАТА',
      'add': 'Добавить',
      'home': 'Главная',
      'wallet': 'Кошелек',
    },
    'kk_KK': {
      'sign_in': 'Кіру',
      'email_address': 'Электронды пошта',
      'password': 'Құпия сөз',
      'swipe_left': 'Аккаунт жоқ па? Солға свайп жаса',
      'sign_up': 'Тіркелу',
      'username': 'Қолданушының есімі',
      'verify_password': 'Құпия сөзді мақұлда',
      'swipe_right': 'Аккаунт бар ма? Оңға свайп жаса',
      'good_afternoon': 'Қайырлы кеш,',
      'expense_history': 'Шығындар тарихы',
      'today': 'Бүгін',
      'this_week': 'Осы апта',
      'this_month': 'Осы ай',
      'appearance': 'Сырт көрініс',
      'light': 'Жарық',
      'dark': 'Қараңғы',
      'language': 'Тіл',
      'english': 'Ағылшынша',
      'kazakh': 'Қазақша',
      'russian': 'Орысша',
      'account_info': 'Аккаунт ақпараты',
      'log_out': 'Шығу',
      'profile': 'Профиль',
      'uncategorized': 'Категориясыз',
      'housing': 'Баспана',
      'transportation': 'Транспорт',
      'food': 'Тамақтану',
      'health_and_medical': 'Денсаулық және медицина',
      'personal_care': 'Жеке гигиена',
      'entertainment': 'Ойын-сауық',
      'debt_payments': 'Қарыздар',
      'education': 'Білім беру',
      'clothing_and_accessories': 'Киім және аксессуарлар',
      'savings_and_investments': 'Жинақтар мен инвестициялар',
      'top_spending_categories': 'Самые большие категории расходов',
      'statistics': 'Статистика',
      'week': 'Апта',
      'month': 'Ай',
      'year': 'Жыл',
      'monday': 'Дс',
      'tuesday': 'Сс',
      'wednesday': 'Ср',
      'thursday': 'Бс',
      'friday': 'Жм',
      'saturday': 'Сб',
      'sunday': 'Жк',
      'add_expense': 'Шығын Қосу',
      'category': 'КАТЕГОРИЯ',
      'name': 'АТЫ',
      'amount': 'ҚҰНЫ',
      'date': 'ДАТА',
      'add': 'Қосу',
      'home': 'Басты',
      'wallet': 'Әмиян',
    },
  };

}